using System.Reflection;

namespace Afrowave.Toolbox.WhenItFails.Tests.PublicApi;

public sealed class StableReleaseExportedTypeManifestContractTests
{
    [Fact]
    public void ExportedTypes_MatchFrozenFirstStableManifest()
    {
        string[] expected =
        [
            "Afrowave.Toolbox.WhenItFails.Bootstrap.DefaultJsonsTemplateProvider",
            "Afrowave.Toolbox.WhenItFails.Bootstrap.JsonsBootstrapFileResult",
            "Afrowave.Toolbox.WhenItFails.Bootstrap.JsonsBootstrapPayload",
            "Afrowave.Toolbox.WhenItFails.Bootstrap.JsonsBootstrapper",
            "Afrowave.Toolbox.WhenItFails.Bootstrap.JsonsTemplateFile",
            "Afrowave.Toolbox.WhenItFails.Catalog.ErrorCatalogContext",
            "Afrowave.Toolbox.WhenItFails.Catalog.ErrorCatalogProviderPayload",
            "Afrowave.Toolbox.WhenItFails.Catalog.ErrorCategoryCatalogProviderPayload",
            "Afrowave.Toolbox.WhenItFails.Catalog.ErrorCodeGroupCatalogProviderPayload",
            "Afrowave.Toolbox.WhenItFails.Catalog.ErrorOwnerCatalogProviderPayload",
            "Afrowave.Toolbox.WhenItFails.Catalog.ErrorProfileCatalogProviderPayload",
            "Afrowave.Toolbox.WhenItFails.Configuration.JsonsOptions",
            "Afrowave.Toolbox.WhenItFails.Configuration.WhenItFailsOptions",
            "Afrowave.Toolbox.WhenItFails.Definitions.ErrorCatalogDocument",
            "Afrowave.Toolbox.WhenItFails.Definitions.ErrorCategoryCatalogDocument",
            "Afrowave.Toolbox.WhenItFails.Definitions.ErrorCategoryDefinition",
            "Afrowave.Toolbox.WhenItFails.Definitions.ErrorCodeGroupCatalogDocument",
            "Afrowave.Toolbox.WhenItFails.Definitions.ErrorCodeGroupDefinition",
            "Afrowave.Toolbox.WhenItFails.Definitions.ErrorDefinition",
            "Afrowave.Toolbox.WhenItFails.Definitions.ErrorOwnerCatalogDocument",
            "Afrowave.Toolbox.WhenItFails.Definitions.ErrorOwnerDefinition",
            "Afrowave.Toolbox.WhenItFails.Definitions.ErrorProfileCatalogDocument",
            "Afrowave.Toolbox.WhenItFails.Definitions.ErrorProfileDefinition",
            "Afrowave.Toolbox.WhenItFails.Descriptors.ErrorDescriptor",
            "Afrowave.Toolbox.WhenItFails.Descriptors.ErrorDescriptor`1",
            "Afrowave.Toolbox.WhenItFails.Descriptors.ErrorDescriptorRequest",
            "Afrowave.Toolbox.WhenItFails.Documentation.DocumentationKeyFormat",
            "Afrowave.Toolbox.WhenItFails.Documentation.DocumentationKeyGenerator",
            "Afrowave.Toolbox.WhenItFails.Enums.ErrorCatalogContextSource",
            "Afrowave.Toolbox.WhenItFails.Enums.ErrorCatalogInitializationMode",
            "Afrowave.Toolbox.WhenItFails.Enums.ErrorCatalogRuntimeState",
            "Afrowave.Toolbox.WhenItFails.Enums.ErrorCatalogValidationSeverity",
            "Afrowave.Toolbox.WhenItFails.Initialization.ErrorCatalogInitializationPayload",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IBuiltInErrorCatalogContextProvider",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCatalog",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCatalogContextProvider",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCatalogContextPublicationReader",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCatalogContextPublisher",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCatalogContextStore",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCatalogDocumentNormalizer",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCatalogFactory",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCatalogInitializer",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCatalogLoader",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCatalogProvider",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCatalogRuntime",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCatalogRuntimeActivationReader",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCatalogRuntimeCombinedObservationReader",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCatalogRuntimeFullObservationReader",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCatalogRuntimePublicationReader",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCatalogRuntimeSupportingObservationReader",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCatalogValidator",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCategoryCatalogLoader",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCategoryCatalogProvider",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCategoryCatalogValidator",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCodeGroupCatalogLoader",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCodeGroupCatalogProvider",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCodeGroupCatalogValidator",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorDefinitionResolver",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorDescriptorFactory",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorDescriptorResolver",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorDescriptorService",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorOwnerCatalogLoader",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorOwnerCatalogProvider",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorOwnerCatalogValidator",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorProfileCatalogLoader",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorProfileCatalogProvider",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorProfileCatalogValidator",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorProfileResolver",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IErrorProfileSelectionService",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IJsonsBootstrapper",
            "Afrowave.Toolbox.WhenItFails.Interfaces.IJsonsTemplateProvider",
            "Afrowave.Toolbox.WhenItFails.Loading.JsonCatalogDocumentWriter",
            "Afrowave.Toolbox.WhenItFails.Loading.JsonErrorCatalogLoader",
            "Afrowave.Toolbox.WhenItFails.Loading.JsonErrorCategoryCatalogLoader",
            "Afrowave.Toolbox.WhenItFails.Loading.JsonErrorCodeGroupCatalogLoader",
            "Afrowave.Toolbox.WhenItFails.Loading.JsonErrorOwnerCatalogLoader",
            "Afrowave.Toolbox.WhenItFails.Loading.JsonErrorProfileCatalogLoader",
            "Afrowave.Toolbox.WhenItFails.Normalization.ErrorCatalogDocumentNormalizer",
            "Afrowave.Toolbox.WhenItFails.Normalization.ErrorCategoryCatalogDocumentNormalizer",
            "Afrowave.Toolbox.WhenItFails.Normalization.ErrorCodeGroupCatalogDocumentNormalizer",
            "Afrowave.Toolbox.WhenItFails.Normalization.ErrorOwnerCatalogDocumentNormalizer",
            "Afrowave.Toolbox.WhenItFails.Normalization.ErrorProfileCatalogDocumentNormalizer",
            "Afrowave.Toolbox.WhenItFails.Normalization.ErrorProfileDefinitionNormalizer",
            "Afrowave.Toolbox.WhenItFails.Normalization.TextKeyNormalizer",
            "Afrowave.Toolbox.WhenItFails.Resolution.ErrorProfileResolver",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCatalogActivationStatusSnapshot",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCatalogCombinedSnapshot",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCatalogCombinedSnapshotExtensions",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCatalogCompletedCombinedSnapshot",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCatalogCompletedFullSnapshot",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCatalogCompletedSupportingCatalogsSnapshot",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCatalogContextPublication",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCatalogFullSnapshot",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCatalogPublishedCombinedSnapshot",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCatalogPublishedCombinedSnapshotExtensions",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCatalogPublishedSupportingCatalogsSnapshot",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCatalogPublishedSupportingCatalogsSnapshotExtensions",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCatalogRuntimeStatus",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCatalogSnapshotExtensions",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCatalogValidationIssueSnapshot",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCatalogValidationSnapshot",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCatalogValidationSnapshotExtensions",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCategoryCatalogSnapshot",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCategoryCatalogSnapshotExtensions",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCategoryDefinitionSnapshot",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCodeGroupCatalogSnapshot",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCodeGroupCatalogSnapshotExtensions",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorCodeGroupDefinitionSnapshot",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorDefinitionSnapshot",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorOwnerCatalogSnapshot",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorOwnerCatalogSnapshotExtensions",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorOwnerDefinitionSnapshot",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorProfileCatalogSnapshot",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorProfileCatalogSnapshotExtensions",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorProfileDefinitionSnapshot",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorSupportingCatalogsSnapshot",
            "Afrowave.Toolbox.WhenItFails.Runtime.ErrorSupportingCatalogsSnapshotExtensions",
            "Afrowave.Toolbox.WhenItFails.Validation.ErrorCatalogCrossValidator",
            "Afrowave.Toolbox.WhenItFails.Validation.ErrorCatalogValidationIssue",
            "Afrowave.Toolbox.WhenItFails.Validation.ErrorCatalogValidationResult",
            "Afrowave.Toolbox.WhenItFails.Validation.ErrorCatalogValidator",
            "Afrowave.Toolbox.WhenItFails.Validation.ErrorCategoryCatalogValidator",
            "Afrowave.Toolbox.WhenItFails.Validation.ErrorCodeGroupCatalogValidator",
            "Afrowave.Toolbox.WhenItFails.Validation.ErrorOwnerCatalogValidator",
            "Afrowave.Toolbox.WhenItFails.Validation.ErrorProfileCatalogValidator",
            "Microsoft.Extensions.DependencyInjection.WhenItFailsServiceCollectionExtensions"
        ];

        string[] actual = typeof(Afrowave.Toolbox.WhenItFails.Interfaces.IErrorCatalogRuntime)
            .Assembly
            .GetExportedTypes()
            .Select(type => type.FullName ?? type.Name)
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToArray();

        Array.Sort(expected, StringComparer.Ordinal);

        Assert.Equal(expected, actual);
    }
}
